In [1]:
import numpy as np
import os
from collections import Counter

In [2]:
folder='Email/'

In [3]:
files=os.listdir(folder)
len(files)

5172

In [4]:
Emails=[folder + file for file in files]
len(Emails)

5172

In [5]:
word=[]
for Email in Emails:
    f=open(Email,encoding='latin-1')
    blob=f.read()
    word=word+blob.split(" ")
        

In [6]:
len(word)

1083821

In [7]:
for i in range(len(word)):
    if not word[i].isalpha():
        word[i]=""

In [8]:
word_dict=Counter(word)
len(word_dict)

40577

In [9]:
del word_dict[""]

In [10]:
word_dict=word_dict.most_common(3000)
word_dict

[('the', 22003),
 ('to', 16118),
 ('ect', 11643),
 ('and', 11337),
 ('for', 9430),
 ('of', 9382),
 ('a', 8815),
 ('you', 7289),
 ('hou', 7283),
 ('in', 6885),
 ('on', 6723),
 ('is', 6664),
 ('this', 5895),
 ('enron', 5282),
 ('i', 4748),
 ('be', 4623),
 ('that', 4267),
 ('will', 3783),
 ('have', 3746),
 ('with', 3570),
 ('your', 3506),
 ('at', 3371),
 ('we', 3349),
 ('s', 3219),
 ('are', 3045),
 ('it', 2942),
 ('by', 2852),
 ('com', 2802),
 ('as', 2793),
 ('from', 2783),
 ('gas', 2756),
 ('or', 2723),
 ('not', 2653),
 ('me', 2416),
 ('deal', 2381),
 ('if', 2359),
 ('meter', 2179),
 ('hpl', 2116),
 ('please', 1959),
 ('re', 1954),
 ('e', 1774),
 ('any', 1766),
 ('our', 1765),
 ('corp', 1753),
 ('can', 1717),
 ('d', 1699),
 ('all', 1594),
 ('has', 1562),
 ('was', 1538),
 ('know', 1465),
 ('need', 1357),
 ('an', 1357),
 ('forwarded', 1292),
 ('new', 1291),
 ('t', 1288),
 ('may', 1273),
 ('up', 1251),
 ('j', 1239),
 ('mmbtu', 1193),
 ('should', 1157),
 ('do', 1157),
 ('am', 1103),
 ('get',

In [11]:
for i in word_dict:
    print(i[0])

the
to
ect
and
for
of
a
you
hou
in
on
is
this
enron
i
be
that
will
have
with
your
at
we
s
are
it
by
com
as
from
gas
or
not
me
deal
if
meter
hpl
please
re
e
any
our
corp
can
d
all
has
was
know
need
an
forwarded
new
t
may
up
j
mmbtu
should
do
am
get
out
see
no
there
price
daren
but
been
company
l
these
let
so
would
m
into
xls
farmer
attached
us
information
they
message
day
time
my
one
what
only
http
th
volume
mail
contract
which
month
more
robert
sitara
about
texas
nom
energy
pec
questions
www
deals
volumes
pm
ena
now
their
file
some
email
just
also
call
change
other
here
like
b
flow
net
following
p
production
when
over
back
want
original
them
below
o
ticket
c
he
could
make
inc
report
march
contact
were
days
list
nomination
system
who
april
number
sale
don
its
first
thanks
business
help
per
through
july
forward
font
free
daily
use
order
today
r
had
fw
set
plant
statements
go
gary
oil
line
sales
w
effective
well
tenaska
take
june
x
within
nbsp
she
how
north
america
being
under
next
week
t

quarter
course
chairman
petroleum
notes
medications
ei
instead
fine
lake
pre
force
seek
recipient
gain
placed
age
least
body
asking
discussed
hanson
emails
nominate
ext
known
ones
ed
assigned
htmlimg
means
present
various
invoices
gd
agency
along
located
reflects
solutions
ex
house
cds
br
owner
apr
sullivan
basin
linda
worked
car
seen
properties
booked
higher
store
est
revenue
wait
women
far
met
wholesale
range
kcs
recorded
brown
lots
match
input
grant
providing
huge
investor
kelly
apply
paths
handling
pipes
advantage
analysis
focus
draw
red
origination
connection
planning
wilson
golf
summary
item
bankruptcy
expenses
pgev
encina
beaty
memo
initial
thousand
mills
penis
friend
conversation
multiple
martin
names
bit
dth
talked
behalf
preliminary
button
herein
gisb
coupon
sa
oi
appears
door
texaco
csikos
arrangements
cpr
expires
popular
sending
research
conditions
gb
board
ca
applications
tried
paying
acquisition
reporting
normal
maintenance
resume
announced
attachment
buyer
objectives
pro

sir
vary
sounds
disclose
authority
flw
straight
worldnet
beemer
ooo
defs
thorough
officers
flight
prefer
awesome
macintosh
feet
constitutes
formosa
porn
armstrong
driscoll
watches
newsietter
twenty
tommy
fields
method
setup
allocating
initially
missed
clarification
especially
dorcheus
del
millions
insurance
pooling
trial
tennessee
ellis
direction
bold
catch
performing
accepted
matters
batch
continuing
winning
symbol
offsystem
decisions
produced
ended
greatest
degree
solmonson
imbalances
fall
fear
hate
fight
reallocated
debt
reform
australia
plain
prompt
remains
ifhsc
enhancements
connevey
jay
valued
lay
infrastructure
military
allowing
ff
dry


In [12]:
features=[]
labels=[] 

for Email in Emails:
    f=open(Email,encoding='latin-1')
    blob=f.read().split()
    data=[]
    
    for i in word_dict:
        data.append(blob.count(i[0]))
    features.append(data)
    
    if 'spam' in Email:
        labels.append(1)
    if 'ham' in Email :
        labels.append(0)

In [13]:
len(features)

5172

In [14]:
len(labels)

5172

In [15]:
features=np.array(features)
features

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 8,  8, 17, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 2,  7,  0, ...,  0,  0,  0],
       [19, 21,  0, ...,  0,  0,  0]])

In [16]:
labels=np.array(labels)
labels

array([0, 0, 0, ..., 1, 1, 0])

In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(features,labels,test_size=0.2,random_state=7)

In [21]:
X_train.shape

(4137, 3000)

In [22]:
X_test.shape

(1035, 3000)

In [23]:
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB()

In [24]:
classifier.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [35]:
 new_email="Hi you have won a lottery of 10 lacs. to get your reward kindly share your phone number."

In [36]:
#new_email="hii there"

In [37]:
input_mail=[]
for i in word_dict:
    input_mail.append(new_email.split(" ").count(i[0]))

In [38]:
input_mail=np.array(input_mail)
input_mail

array([0, 1, 0, ..., 0, 0, 0])

In [39]:
classifier.predict(input_mail.reshape(1,3000))

array([1])

In [40]:
y_pred=classifier.predict(X_test)

In [41]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9545893719806763

In [42]:
import pickle

In [43]:
pickle.dump(classifier,open('model.pkl','wb'))

In [44]:
pickle.dump(word_dict,open('mystrings.pkl','wb'))